### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by v1rtl** [tmcdonell/config-alacritty#1]
```
Created log file at "/tmp/Alacritty-925.log"
[2019-11-13 22:09] [ERROR] Failed to spawn command: No such file or directory (os error 2)
```

`alacritty` version: 0.3.3
shell: fish 3.0.2

**Comment by tmcdonell** [comment]
Maybe you don't have `tmux` installed? [See here.](https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml#L498)

**Comment by v1rtl** [comment]
> Maybe you don't have `tmux` installed? [See here.](https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml#L498)

Looks like this line breaks everything.

https://github.com/tmcdonell/config-alacritty/blob/880fc4e1ac923818c994befe34ecf3f6ebd8afac/alacritty.yml#L499

I don't use `homebrew`, maybe just use from $PATH, like `fish`?

And I have `tmux` installed

**Comment by tmcdonell** [comment]
At this point `$PATH` does not exist, so you need to provide a full path to the executable you want to launch. You are free to change that to whatever shell you want to use.
